//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace integrador_moodle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aluno
    {
        public Aluno()
        {
            this.Matricula = new HashSet<Matricula>();
        }
    
        public int alunoUID { get; set; }
        public string nome { get; set; }
        public string cpf { get; set; }
        public System.DateTime dataNascimento { get; set; }
        public int sexo { get; set; }
        public string celular { get; set; }
        public string telefoneFixo { get; set; }
        public string endereco { get; set; }
        public string bairro { get; set; }
        public string cidade { get; set; }
        public string cep { get; set; }
        public string estado { get; set; }
        public string login { get; set; }
        public string senha { get; set; }
        public string email { get; set; }
    
        public virtual ICollection<Matricula> Matricula { get; set; }
    }
}
