//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace integrador_moodle.Models
{
    using System;
    using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
    
    public partial class Aluno
    {
        public Aluno()
        {
            this.Matricula = new HashSet<Matricula>();
        }
    
        public int alunoUID { get; set; }

        
        [StringLength(100, ErrorMessage = "O tamanho máximo são 100 caracteres."), Required]
        public string nome { get; set; }

        [StringLength(11, ErrorMessage = "O tamanho máximo são 11 caracteres."), Required]
        public string cpf { get; set; }

        [Required]
        [DataType(DataType.Date), DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime dataNascimento { get; set; }

        [Required]
        public int sexo { get; set; }

        [Required]
        public string celular { get; set; }
        
        [Required]
        public string telefoneFixo { get; set; }
        
        [Required]
        public string endereco { get; set; }
        
        [Required]
        public string bairro { get; set; }

        [Required]
        public string cidade { get; set; }

        [Required]
        public string cep { get; set; }

        [Required]
        public string estado { get; set; }

        public string login { get; set; }

        [Required]
        public string senha { get; set; }        
        
        [Required]
        [DataType(DataType.EmailAddress)]
        public string email { get; set; }
    
        public virtual ICollection<Matricula> Matricula { get; set; }
    }
}
