//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace integrador_moodle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curso
    {
        public Curso()
        {
            this.Matricula = new HashSet<Matricula>();
        }
    
        public int cursoUID { get; set; }
        public string nomeBreve { get; set; }
        public string fullname { get; set; }
        public string descricao { get; set; }
        public string objetivos { get; set; }
        public string competencias { get; set; }
        public string publicoalvo { get; set; }
        public string topicos { get; set; }
        public string descricaoFormaPagamento { get; set; }
        public int idmoodle { get; set; }
    
        public virtual ICollection<Matricula> Matricula { get; set; }
    }
}
