//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace integrador_moodle.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class integradorEntities : DbContext, ContextI
    {
        public integradorEntities()
            : base("name=integradorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Certificado> Certificado { get; set; }
        public DbSet<FormaPagamento> FormaPagamento { get; set; }
        public DbSet<Matricula> Matricula { get; set; }
        public DbSet<Pagamento> Pagamento { get; set; }
        public DbSet<UsuarioAdmin> UsuarioAdmin { get; set; }
        public DbSet<Curso> Curso { get; set; }
        public DbSet<Aluno> Aluno { get; set; }
        public DbSet<UF> UF { get; set; }
        public DbSet<BandeiraCartao> BandeiraCartao { get; set; }
    }
}
