//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace integrador_moodle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pagamento
    {
        public int pagamentoUID { get; set; }
        public int matriculaUID { get; set; }
        public int formaPagamentoUID { get; set; }
        public decimal valor { get; set; }
        public int parcelas { get; set; }
    
        public virtual FormaPagamento FormaPagamento { get; set; }
        public virtual Matricula Matricula { get; set; }
    }
}
