//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace integrador_moodle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioAdmin
    {
        public int usuarioUID { get; set; }
        public string login { get; set; }
        public string senha { get; set; }
    }
}
